core/src/bms/player/beatoraja/select/BarRenderer.java
A feature to add logical operators to random select filters, particularly for keys with integer values. Implements "<", ">", "<=", ">=" and "&&" operations. 
Normally, beatoraja as of 0.8.6 allows for fixed value keys in random select filters, such as "clear": 6, which would select a song with Hard-Clear lamp. It isn't possible to have it select from a range of values, such as 4-5, which would describe all songs with lamp ranging from Easy-Clear to Groove-Clear. This PR allows doing it as such:
```json
{
"name":"RANDOM EASY-GROOVE",
"filter": {
"clear": ">=4 && <6"
}
}
```
This has no effect on normal beatoraja behavior, otherwise. Everything that would work in upstream still holds, it only expands on it.
=> logical operators for random select filters

core/src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
Normally, Hi-Speed Fix mode isn't displayed in song select menu, if current bar doesn't belong to a song or a course. However, it is still possible to set this value by pressing START+5 - Start menu will not display current value in that case, but it will still update it for 7K mode. 
Every other option is displayed regardless of current bar type and defaults to displaying the value for 7K, if the option is keymode specific.
This commit changes the behavior for hispeedfix getter, so it matches that of other options.
=> fix hispeedfix display without selected song

core/src/bms/player/beatoraja/song/SQLiteSongDatabaseAccessor.java
Catch NPE on failed bms parse. Very rare but happens with some `bmson` charts, also added to `bm*` for posterity.
Will log the offending charts rather than an ambiguous NPE trace some function calls higher.
=> Useful error message on failed bms parse

core/src/bms/player/beatoraja/play/JudgeManager.java
I studied autoadjust logic in LR2 disassembly and recreated that logic here.
It fixes an issue of beatoraja autoadjust being too reactive, which results in too big changes of adjust at bursts, which results in a net negative for score.
On the other hand, it won't be able to reach the generally correct offset as quickly, but it's not as important. Previous logic is very capable of completely ruining the plays, which is the reason to choose against it for many.
Doesn't impact the game in any other way. Currently is under user testing.
Reference disassembly with comments in the attached screenshot.
=> LR2 judge autoadjust logic

core/src/bms/player/beatoraja/MainController.java, core/src/bms/player/beatoraja/result/MusicResult.java
Original beatoraja code sends the scores only on prepare() method of MusicResult scene. Before the send thread finishes its job, result screen will never let you go back to music select, so in the case IR lags, you have to wait until timeout. Failed to send scores are then resent on next MusicResult.prepare() call.
This PR allows to return to song select if the score takes more than 3 seconds to submit.
Failed to submit scores are resent to IR every 4^retry seconds in a background thread, which starts if connection to IR on game start succeeded. 
Code to resend scores from result scene is deleted, only the immediate score is sent from result screen. 
The number of maximum retries is set in "config_sys.json" file in the parameter "irSendCount", default value is 5. After failing to send the …
=> IR sendPlayData use flow rework

core/src/bms/player/beatoraja/play/PracticeConfiguration.java, core/src/bms/player/beatoraja/skin/SkinNoteDistributionGraph.java, core/src/bms/player/beatoraja/skin/json/JsonSkin.java, core/src/bms/player/beatoraja/skin/json/JsonSkinObjectLoader.java, core/src/bms/player/beatoraja/skin/lr2/LR2CourseResultSkinLoader.java, core/src/bms/player/beatoraja/skin/lr2/LR2PlaySkinLoader.java, core/src/bms/player/beatoraja/skin/lr2/LR2ResultSkinLoader.java, core/src/bms/player/beatoraja/skin/lr2/LR2SelectSkinLoader.java
Remove measure gaps for cleaner notegraphs. These typically appear heavily aliased in skins.
Before:
After:
Measures can still be distinguished by heights of different bars and colour within.
=> Add noGapX to remove width gaps in note graphs

core/src/bms/player/beatoraja/result/MusicResult.java
I made an oversight in the PR that is already merged, it had a bug that it would never send a score for any but the primary IR server, in case multiple IRs are connected.
=> IR send rework: bugfix for multiple IRs

core/src/bms/player/beatoraja/modmenu/RandomTrainer.java
Fixes an issue #27 by initializing laneOrder variable. The crash occurs on first "Trainer Enable", if blackwhite permute was enabled, because the method GetLaneOrder is called before the first call to SetLaneOrder. If bw permute is enabled, GetLaneOrder will try to access the contents of laneOrder, which don't yet exist.
=> Fix crash on first GetLaneOrder call with bw permute

src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
allows skins to fetch lane assignments during Play stage
=> Extend GetAssignedLane to BMSPlayer

core/src/bms/player/beatoraja/play/BMSPlayer.java
This blocks the ability to change settings like green number or lanecover through holding START or SELECT at play scene, when you are at "stopped playing" sub-states. This greatly reduces the number of accidental value changes when playing on controller, as START button can be pressed to skip the fade-out animation, and your turntable may be spinning at this moment from inertia of last scratch note, resulting in unintentional lanecover position change.
=> block start and sel settings on play end sub-states

core/src/bms/player/beatoraja/audio/MSADPCMDecoder.java, core/src/bms/player/beatoraja/audio/PCM.java
Close #37
I've tested on these BMS that use MS-ADPCM:
* Romancing Sa・Ga3 ～四魔貴族バトル2～
* エストポリス伝記II ～バトル# 3～
* フランの中できゅっ☆としてドカーン†
All these WAVs are stereo. I can't find any WAV files with more than two channels to test with, but the handling of this part of the code should be consistent with ffmpeg's implementation.
=> Fix broken MS-ADPCM decoding implementation

core/src/bms/player/beatoraja/result/MusicResult.java
merge with 0.8.8 caused an issue, creating a second score send queue, which was partially used, while the previous queue was also used partially... resulting in no work being done in total (lol)
Also reduces the wait time before one can exit the result scene from 3 seconds to 1 second.
=> Fix post-merge bug where scores woudn't send

core/src/bms/player/beatoraja/audio/MSADPCMDecoder.java
Very minor fix for a build error in #61 - could do with a quick test in-game as I don't have any affected charts on hand.
Build test run: https://github.com/llm96/lr2oraja-endlessdream/actions/runs/14550170295
=> Fix build error in MSADPCMDecoder.java

.github/workflows/prerelease.yml, README.md, buildSrc/src/main/kotlin/org/endlessdream/extra/PlatformFilter.kt, buildSrc/src/main/kotlin/org/endlessdream/extra/multiplatform-convention.gradle.kts, core/build.gradle.kts, core/src/bms/player/beatoraja/MainController.java, core/src/bms/player/beatoraja/MainLoader.java, core/src/bms/player/beatoraja/SpriteBatchHelper.java, core/src/bms/player/beatoraja/config/KeyConfiguration.java, core/src/bms/player/beatoraja/play/bga/FFmpegProcessor.java, core/src/bms/player/beatoraja/select/MusicSelectCommand.java, core/src/bms/player/beatoraja/select/SearchTextField.java, gradle/libs.versions.toml
This commit makes it possible to run endless dream on MacOS(arm based, one x86 mac user confirms it is working).
- Upgrade imgui 1.86.11 -> 1.86.12 and sqlite 3.23.1 -> 3.42.0 and a
new property `arch`(`x86-64` or `aarch64`) to get support for macos
binding and the correct dependency.
- Replace `new SpriteBatch()` with
`SpriteBatchHelper.createSpriteBatch()`. Default `SpriteBatch`
constructor involves a shader that macos cannot complie.
- Replace `ShapeRenderer` with `ShapeDrawer`, the old one has the
similar shader problem which directly crashes when opening key-config
menu.
- Upgrading libgdx 1.12.1 -> 1.13.0 to solve fps issue
- Replace `java.awt.Clipboard` with `javafx.Clipboard`, the clipboard
support from awt is **only** broken on macos.
- Update readme
- Update github workflow
- …
=> Support MacOS(arm based)

core/src/bms/player/beatoraja/ScoreDatabaseAccessor.java, core/src/bms/player/beatoraja/song/SongInformationAccessor.java
Problem: If you happen to have a very big BMS directory, this exception might occur:
```
严重: スコア取得時の例外:[SQLITE_TOOBIG] String or BLOB exceeds size
limit (statement too long) Query: SELECT * FROM score WHERE sha256 IN
(...)`
```
And the whole sqlite query statement would be printed in log file.
This commit fixed two overlength sql generate code place by forcing them to query data chunk by chunk. And one chunk size is set to be 1000.
=> BugFix: Avoid constructing overlength sql

buildSrc/src/main/kotlin/org/endlessdream/extra/PlatformFilter.kt
This pr fixes the wrong filter strategy which only affects the x86 macos: the correct lwjgl dependency suffix name should be `macos` rather than `macos-x86_64`. The test has already been done on a real x86 mac.
Here is a small list for comparing:
- MacOS(arm): `lwjgl-natives-macos-arm64.jar`
- MacOS(x86): `lwjgl-natives-macos.jar`
- Windows(arm): `lwjgl-natives-windows-x86.jar` / `lwjgl-natives-windows.jar` (no idea why)
- Windows(x86): `lwjgl-natives-windows-arm64.jar`
See [here](https://www.lwjgl.org/browse/stable/bin/lwjgl) for reference
=> Fix wrong lwjgl dependency suffix for x86 macos

core/src/bms/player/beatoraja/MainController.java, core/src/bms/player/beatoraja/PlayerResource.java, core/src/bms/player/beatoraja/modmenu/ImGuiRenderer.java, core/src/bms/player/beatoraja/modmenu/SongManagerMenu.java
close #26 
This commit adds a new menu called `Song Manager`, which is designed for rendering current song's status and providing easy access to some operations (e.g. reverse table lookup & favorite folder management).
As for now, the menu shows the `best record set time` as a "current song's status" example and `reverse table lookup` button as an "extra operations" example.
For future reviewers: this pr picks a temporary solution for adding the difficult tables' symbols, it can be deleted after ImGUI-java upgraded it's dependency version to 1.92 or above. See below comments for details.
=> Add `SongManager` menu for rendering current reverse table lookup

core/src/bms/player/beatoraja/PlayerResource.java, core/src/bms/player/beatoraja/play/BMSPlayer.java, core/src/bms/player/beatoraja/result/MusicResult.java, core/src/bms/player/beatoraja/skin/property/StringPropertyFactory.java
close #45 
This pr should fix two problems that pointed out:
- Disabling the freq trainer will confuse endless dream and think it's a normal score and submit it to IRs
- Title will be changed when changing freq during the game play
by persisting some "flags/data".
This pr intentionally leaves the local score save related code unchanged. Also the clear type won't be NO_PLAY if the user used the trick above.
=> Persist some freq related data to avoid changing freq during gameplay

core/src/bms/player/beatoraja/modmenu/SongManagerMenu.java, core/src/bms/player/beatoraja/select/BarManager.java, core/src/bms/player/beatoraja/select/MusicSelectInputProcessor.java, core/src/bms/player/beatoraja/skin/property/IntegerPropertyFactory.java
This PR adds a song manager mod menu checkmark to temporarily sort charts by their last played date.
On Catizard's request, the previously displayed score date in the same menu is removed.
While this option is enabled, the skin's sort property is hidden, which I think should work acceptably with most skins.
Pressing keyboard 2 while this sort option is enabled will disable it and restore normal functionality.
Should close https://github.com/seraxis/lr2oraja-endlessdream/issues/95
=> Last played sort

core/src/bms/player/beatoraja/Config.java, core/src/bms/player/beatoraja/MainController.java, core/src/bms/player/beatoraja/launcher/MusicSelectConfigurationView.fxml, core/src/bms/player/beatoraja/launcher/MusicSelectConfigurationView.java, core/src/resources/UIResources.properties
Addresses #23. This PR adds a config option under the "Music Select" tab in the launcher to allow skipping the decide screen when selecting a song.
- This option is disabled by default in the launcher
- When selecting a song, the game switches directly to the play scene instead of switching to the decide scene, skipping the animation and decide BGM sound.
https://github.com/user-attachments/assets/140b7c78-855c-485c-bb96-1d7bfbe830b7
https://github.com/user-attachments/assets/72e4fd5b-c6a6-47aa-9447-7c1e09e05cf8
=> #23: Option to skip decide screen

core/src/bms/player/beatoraja/MainController.java, core/src/bms/player/beatoraja/MainLoader.java, core/src/bms/player/beatoraja/MainState.java, core/src/bms/player/beatoraja/PerformanceMetrics.java, core/src/bms/player/beatoraja/modmenu/ImGuiRenderer.java, core/src/bms/player/beatoraja/modmenu/PerformanceMonitor.java, core/src/bms/player/beatoraja/select/BarManager.java, core/src/bms/player/beatoraja/select/MusicSelector.java, core/src/bms/player/beatoraja/skin/SkinTextBitmap.java, core/src/bms/player/beatoraja/skin/json/JSONSkinLoader.java, core/src/bms/player/beatoraja/skin/json/JsonPlaySkinObjectLoader.java, core/src/bms/player/beatoraja/skin/json/JsonSelectSkinObjectLoader.java, core/src/bms/player/beatoraja/skin/lua/LuaSkinLoader.java
This PR adds `PerformanceMetrics.java`, a helper interface for measuring execution time of selected code blocks, and `PerformanceMonitor.java`, a mod menu window that presents the results.
PerformanceMetrics comes with two methods:
`Event` for measuring one-time or rarely executed sections; these measurements can freely nest and will display as such in the monitor.
(to be used as a variable initializer in a `try-with` block - usage example from `BarManager.java`):
``` java
try (var perf = PerformanceMetrics.get().Event("Saved table load")) {
unsortedtables = tdaccessor.readAll();
}
```
`Watch` for code that runs several times; these measurements are displayed as aggregate statistics instead of individual results. They're also slightly more performant than events.  (`MainLoader.java`): …
=> Initial performance monitoring support
